# Generated by Django 4.2.4 on 2023-08-30 17:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('marca', models.CharField(max_length=100)),
                ('preco_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_imagens', models.PositiveIntegerField(default=5)),
                ('disponibilidade', models.BooleanField(default=True, verbose_name='Em estoque')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('imagem_principal', models.ImageField(upload_to='produto_imagens')),
                ('imagem_adicional_1', models.ImageField(blank=True, upload_to='produto_imagens')),
                ('imagem_adicional_2', models.ImageField(blank=True, upload_to='produto_imagens')),
                ('imagem_adicional_3', models.ImageField(blank=True, upload_to='produto_imagens')),
                ('imagem_adicional_4', models.ImageField(blank=True, upload_to='produto_imagens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
                ('cores_disponiveis', models.ManyToManyField(blank=True, related_name='produtos', to='produto.cor')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.categoria')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.subcategoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanhos_disponiveis',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produto.tamanho'),
        ),
    ]
