# Generated by Django 4.2.4 on 2023-08-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_categoria_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produto.subcategoria'),
        ),
    ]
