# Generated by Django 4.2.4 on 2023-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_hot_trend',
            field=models.BooleanField(default=False),
        ),
    ]
